### ISSUE TITLE
如何将源码编程成oc2mango可执行文件的啊？

### ISSUE THREAD

**Issue by hnxyzhw** [SilverFruity/oc2mango#1]
1.能否讲解一下如何将源码编程成oc2mango可执行文件的啊？
2.可否编译成应用，直接安装到Mac上？
@SilverFruity

**Comment by SilverFruity** [comment]
## 1. oc2mango可执行文件的主要思路

在oc2mango项目中，Target `oc2mango`，主要有四个过程：输入源码文件文件夹、调用解析器、语法树生成、解析语法树生成mango脚本。

1. 输入源码文件文件夹

   获取命令行参数中的输入文件或文件夹。[关于C获取命令行参数](https://www.cnblogs.com/bobliao/p/9916860.html)

2. 调用解析器

   代码在Parser.m中
   ```objc
    extern void yy_set_source_string(char const *source);
    extern void yyrestart (FILE * input_file );
    extern int yyparse(void);
    //设置使用文件数据自定义数据源
    yy_set_source_string([source.source UTF8String]);
    //调用词法分析与语法分析生成语法树
    if (yyparse()) {
      yyrestart(NULL);
      NSLog(@"\n----Error: \n  PATH: %@\n  INFO:%@",self.source.filePath,self.error);
    }
   ```

3. 语法树生成

	* 词法分析器：cal.l，使用lex。
	* 语法分析器：cal.y，使用yacc。根据语法生成节点，添加到语法树。
	* 语法树主要由AST.h和RunnerClasses.h中的类组成

4. 解析语法树生成mango脚本

   代码在Convert.m中，根据语法树中的信息将OC转换为对应的mango脚本。

一些问题:

1. 针对cal.l和cal.y文件，在编译过程中，实际是被编译成了三个文件:  **cal.yy.c**、**y.tab.c**、**y.tab.h**。编译oc2mango时，你可以在编译缓存中找到这三个文件。
2. lex、yacc和objective-C一起使用时，请将**Build Setting**中的`Compile Source As`设置为`Objective-C`



## 2. 针对第二个问题

完全是可以的。

编译成应用时，可以使用CocoaPods导入**oc2mangLib**。

```
pod ~> 'oc2mangoLib'
```

将上述流程的第一步替换为从App输入文件夹路径即可。

**Comment by SilverFruity** [comment]
## 1. oc2mango可执行文件的主要思路

在oc2mango项目中，Target `oc2mango`，主要有四个过程：输入源码文件文件夹、调用解析器、语法树生成、解析语法树生成mango脚本。

1. 输入源码文件文件夹

   获取命令行参数中的输入文件或文件夹。[关于C获取命令行参数](https://www.cnblogs.com/bobliao/p/9916860.html)

2. 调用解析器

   代码在Parser.m中
   ```objc
    extern void yy_set_source_string(char const *source);
    extern void yyrestart (FILE * input_file );
    extern int yyparse(void);
    //设置使用文件数据自定义数据源
    yy_set_source_string([source.source UTF8String]);
    //调用词法分析与语法分析生成语法树
    if (yyparse()) {
      yyrestart(NULL);
      NSLog(@"\n----Error: \n  PATH: %@\n  INFO:%@",self.source.filePath,self.error);
    }
   ```

3. 语法树生成

	* 词法分析器：cal.l，使用lex。
	* 语法分析器：cal.y，使用yacc。根据语法生成节点，添加到语法树。
	* 语法树主要由AST.h和RunnerClasses.h中的类组成

4. 解析语法树生成mango脚本

   代码在Convert.m中，根据语法树中的信息将OC转换为对应的mango脚本。

一些问题:

1. 针对cal.l和cal.y文件，在编译过程中，实际是被编译成了三个文件:  **cal.yy.c**、**y.tab.c**、**y.tab.h**。编译oc2mango时，你可以在编译缓存中找到这三个文件。
2. lex、yacc和objective-C一起使用时，请将**Build Setting**中的`Compile Source As`设置为`Objective-C`



## 2. 针对第二个问题

完全是可以的。

编译成应用时，可以使用CocoaPods导入**oc2mangLib**。

```
pod ~> 'oc2mangoLib'
```

将上述流程的第一步替换为从App输入文件夹路径即可。

@hnxyzhw

**Comment by hnxyzhw** [comment]
> ## 1. oc2mango可执行文件的主要思路
> 在oc2mango项目中，Target `oc2mango`，主要有四个过程：输入源码文件文件夹、调用解析器、语法树生成、解析语法树生成mango脚本。
> 
> 1. 输入源码文件文件夹
>    获取命令行参数中的输入文件或文件夹。[关于C获取命令行参数](https://www.cnblogs.com/bobliao/p/9916860.html)
> 2. 调用解析器
>    代码在Parser.m中
>    ```objc
>     extern void yy_set_source_string(char const *source);
>     extern void yyrestart (FILE * input_file );
>     extern int yyparse(void);
>     //设置使用文件数据自定义数据源
>     yy_set_source_string([source.source UTF8String]);
>     //调用词法分析与语法分析生成语法树
>     if (yyparse()) {
>       yyrestart(NULL);
>       NSLog(@"\n----Error: \n  PATH: %@\n  INFO:%@",self.source.filePath,self.error);
>     }
>    ```
> 3. 语法树生成
>    
>    * 词法分析器：cal.l，使用lex。
>    * 语法分析器：cal.y，使用yacc。根据语法生成节点，添加到语法树。
>    * 语法树主要由AST.h和RunnerClasses.h中的类组成
> 4. 解析语法树生成mango脚本
>    代码在Convert.m中，根据语法树中的信息将OC转换为对应的mango脚本。
> 
> 一些问题:
> 
> 1. 针对cal.l和cal.y文件，在编译过程中，实际是被编译成了三个文件:  **cal.yy.c**、**y.tab.c**、**y.tab.h**。编译oc2mango时，你可以在编译缓存中找到这三个文件。
> 2. lex、yacc和objective-C一起使用时，请将**Build Setting**中的`Compile Source As`设置为`Objective-C`
> 
> ## 2. 针对第二个问题
> 完全是可以的。
> 
> 编译成应用时，可以使用CocoaPods导入**oc2mangLib**。
> 
> ```
> pod ~> 'oc2mangoLib'
> ```
> 
> 将上述流程的第一步替换为从App输入文件夹路径即可。
> 
> @hnxyzhw

OK，感谢，非常详细。
