### ISSUE TITLE
一个奇葩问题

### ISSUE THREAD

**Issue by jjj4me** [SilverFruity/oc2mango#6]
![截屏2023-05-25 20 09 03](https://github.com/SilverFruity/oc2mango/assets/131424439/88d4e38b-8a65-4f5c-836b-607fe45db2aa)

很奇葩的问题，中文文字“库”后面紧跟一个转义字符和双引号，就会失败

**Comment by SilverFruity** [comment]
应该好了

**Comment by jjj4me** [comment]
可以了，作者处理问题好快！👍🏻👍🏻👍🏻👍🏻
